Query : {
    _mongooseOptions: {},
    _transforms: [],
    _hooks: Kareem { _pres: Map(0) {}, _posts: Map(0) {} },
    _executionStack: null,
    mongooseCollection: Collection {
      collection: Collection { s: [Object], client: [MongoClient] },
      Promise: [Function: Promise],
      modelName: 'User',
      _closed: false,
      opts: {
        autoIndex: true,
        autoCreate: true,
        autoSearchIndex: false,
        schemaUserProvidedOptions: [Object],
        capped: false,
        Promise: undefined,
        '$wasForceClosed': undefined
      },
      name: 'users',
      collectionName: 'users',
      conn: NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: {},
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object: null prototype],
        _readyState: 1,
        _closeCalled: undefined,
        _hasOpened: true,
        plugins: [],
        id: 0,
        _queue: [],
        _listening: false,
        _lastHeartbeatAt: null,
        _connectionOptions: [Object],
        _connectionString: 'mongodb+srv://surya-mahi:Surya2006@cluster0.iramp.mongodb.net/videotube',
        client: [MongoClient],
        '$initialConnection': [Promise],
        db: [Db],
        host: 'cluster0-shard-00-02.iramp.mongodb.net',
        port: 27017,
        name: 'videotube',
        [Symbol(mongoose:defaultConnection)]: true
      },
      queue: [],
      buffer: false,
      emitter: EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      }
    },
    model: Model { User },
    schema: Schema {
      obj: {
        username: [Object],
        email: [Object],
        fullName: [Object],
        avatar: [Object],
        coverImage: [Object],
        watchHistory: [Array],
        password: [Object],
        refreshToken: [Object]
      },
      paths: {
        username: [SchemaString],
        email: [SchemaString],
        fullName: [SchemaString],
        avatar: [SchemaString],
        coverImage: [SchemaString],
        watchHistory: [SchemaArray],
        password: [SchemaString],
        refreshToken: [SchemaString],
        _id: [SchemaObjectId],
        createdAt: [SchemaDate],
        updatedAt: [SchemaDate],
        __v: [SchemaNumber]
      },
      aliases: {},
      subpaths: { 'watchHistory.$': [SchemaObjectId] },
      virtuals: { id: [VirtualType] },
      singleNestedPaths: {},
      nested: {},
      inherits: {},
      callQueue: [],
      _indexes: [],
      _searchIndexes: [],
      methods: {
        initializeTimestamps: [Function (anonymous)],
        isPasswordCorrect: [AsyncFunction (anonymous)],
        generateAccessToken: [Function (anonymous)],
        generateRefreshToken: [Function (anonymous)]
      },
      methodOptions: {},
      statics: {},
      tree: {
        username: [Object],
        email: [Object],
        fullName: [Object],
        avatar: [Object],
        coverImage: [Object],
        watchHistory: [Array],
        password: [Object],
        refreshToken: [Object],
        _id: [Object],
        createdAt: [Object],
        updatedAt: [Function: Date],
        __v: [Function: Number],
        id: [VirtualType]
      },
      query: {},
      childSchemas: [],
      plugins: [ [Object], [Object], [Object], [Object], [Object] ],
      '$id': 1,
      mapPaths: [],
      s: { hooks: [Kareem] },
      _userProvidedOptions: { timestamps: true },
      options: {
        strict: true,
        strictQuery: false,
        bufferCommands: true,
        capped: false,
        versionKey: '__v',
        optimisticConcurrency: false,
        minimize: true,
        autoIndex: null,
        discriminatorKey: '__t',
        shardKey: null,
        read: null,
        validateBeforeSave: true,
        validateModifiedOnly: false,
        _id: true,
        id: true,
        typeKey: 'type',
        timestamps: true,
        pluralization: true
      },
      '$timestamps': { createdAt: 'createdAt', updatedAt: 'updatedAt' },
      '$globalPluginsApplied': true
    },
    op: 'findOne',
    options: {},
    _conditions: { _id: '676c62f3123d58c1f98ade61' },
    _fields: undefined,
    _updateDoc: undefined,
    _path: undefined,
    _distinctDoc: undefined,
    _collection: NodeCollection {
      collection: Collection {
        collection: [Collection],
        Promise: [Function: Promise],
        modelName: 'User',
        _closed: false,
        opts: [Object],
        name: 'users',
        collectionName: 'users',
        conn: [NativeConnection],
        queue: [],
        buffer: false,
        emitter: [EventEmitter]
      },
      collectionName: 'users'
    },
    _traceFunction: undefined,
    '$useProjection': true
  }